sudo: required
language: rust
rust:
  - stable
  - beta
  - nightly

scripts:
  - cargo build
  - cargo test

after_success:
  - cargo tarpaulin --all-features --out Xml
  - bash <(curl -s https://codecov.io/bash)