[package]
name = "sync"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
ws = "0.8"
mio = "0.6.19"
serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.39"