on: [push, pull_request]

name: CI

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machine:
          - platform: x86_64-linux
          - platform: aarch64-linux
    steps:
      - uses: actions/checkout@v4
      - if: matrix.machine.platform != 'x86_64-linux'
        uses: docker/setup-qemu-action@v3
      - uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux
      - uses: icewind1991/attic-action@v1
        with:
          name: ci
          instance: https://cache.icewind.me
          authToken: '${{ secrets.ATTIC_TOKEN }}'
      - run: nix build --option system ${{ matrix.machine.platform }}


  build-docker:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        machine:
          - platform: x86_64-linux
          - platform: aarch64-linux
    steps:
      - uses: actions/checkout@v4
      - if: matrix.machine.platform != 'x86_64-linux'
        uses: docker/setup-qemu-action@v3
      - uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux
      - uses: icewind1991/attic-action@v1
        with:
          name: ci
          instance: https://cache.icewind.me
          authToken: '${{ secrets.ATTIC_TOKEN }}'
      - run: nix build --option system ${{ matrix.machine.platform }} .#docker

  docker:
    runs-on: ubuntu-latest
    needs: [build-docker]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: icewind1991/attic-action@v1
        with:
          name: ci
          instance: https://cache.icewind.me
      - run: nix run .#dockerManifest
        if: github.ref == 'refs/heads/master'
        env:
          VERSION: "1.0.0"
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
